version: "3.4"

services:
  mapserver:
    image: camptocamp/mapserver
    ports:
      - "80:80"
    environment:
      - NAIP_GDOWN_ID=16M_kbsLpF3t87KC2n9YgqGEBA5h0lG7U
      - OSM_GDOWN_ID=1snGYjWxs71m6I-qxKsmUzch_bAfQtrEW
    volumes:
      - $PWD/mapserver/mapfiles/mapserver.map:/etc/mapserver/mapserver.map:ro
      - $PWD/mapserver/setup_mapserver.sh:/etc/mapserver/setup_mapserver.sh:ro
    entrypoint: /etc/mapserver/setup_mapserver.sh

  mapproxy:
    build:
      context: mapproxy
      dockerfile: mapproxy/Dockerfile
    network_mode: host

  sitl:
    image: sitl
    build:
      context: sitl
      dockerfile: Dockerfile
      target: sitl
    environment:
      - QT_X11_NO_MITSHM=1
      - DISPLAY=${DISPLAY}
      - LAUNCH_QGC=${LAUNCH_QGC:-1}
      - GAZEBO_HEADLESS=${GAZEBO_HEADLESS}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /dev/shm:/dev/shm
      - /dev/dri:/dev/dri
    network_mode: host
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
