version: "3"

services:
  mapproxy:
    build:
      context: .
      dockerfile: ./docker/mapproxy/Dockerfile
      args:
        CONFIG_FILE: yaml/mapproxy.yaml
        HOST: localhost
        PORT: 8080
    network_mode: host

  px4-sitl:
    build:
      context: .
      dockerfile: ./docker/px4-sitl/Dockerfile
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    network_mode: host
    stdin_open: true
    tty: true
