name: Build and Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows running manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build and publish Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push images to GHCR
        run: |
          docker compose -f docker-compose.yaml push
          docker compose -f docker-compose.yaml -f docker-compose.ardupilot.yaml push
          docker compose -f docker-compose.yaml -f docker-compose.demo.yaml push
          docker compose -f docker-compose.yaml -f docker-compose.ardupilot.yaml -f docker-compose.demo.yaml push
      #- name: Login to Docker Hub
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}
